### ISSUE TITLE
"Attemps max!" - Dataset type 4

### ISSUE THREAD

**Issue by KatieBelli** [ZFTurbo/Music-Source-Separation-Training#127]
![Image](https://github.com/user-attachments/assets/3bf58fed-3f72-4aae-b4e5-5a94dfb017dc)

I tried steps 5000 and 1000 and both show me this error while training.
When I use a very low step number, like 20, the error doesn't appear.

When using dataset type 1, the training goes well and there is no "Attempts max!".

I noticed that it only has issues with certain songs/folders: Both versions of those issue songs are synced and have the same length (in milliseconds).

I would like to use dataset type 4 because I fear that dataset type 1 mixes the 2 versions randomly so that it doesn't train on the synced song as it is but rather a random mixed version (since the document for dataset type 4 states: "_The same as Type 1, but during training all instruments will be from the same position of song._").

Is there a way to check what could cause the issue?

GPU: NVIDIA GeForce 3070 Ti
Total number of training folders: 186
Total number of validation folders: 40

```
audio:
  chunk_size: 130560
  dim_f: 1024
  dim_t: 256
  hop_length: 512
  n_fft: 2048
  num_channels: 2
  sample_rate: 44100
  min_mean_abs: 0.001

model:
  act: gelu
  bottleneck_factor: 4
  growth: 128
  norm: InstanceNorm
  num_blocks_per_scale: 2
  num_channels: 128
  num_scales: 5
  num_subbands: 4
  scale:
  - 2
  - 2

training:
  batch_size: 2
  gradient_accumulation_steps: 3
  grad_clip: 0
  instruments:
  - (...)
  - (...)
  lr: 1.0
  patience: 15
  reduce_factor: 0.95
  target_instrument: null
  num_epochs: 300
  num_steps: 1000
  q: 0.95
  coarse_loss_clip: true
  ema_momentum: 0.999
  optimizer: prodigy
  other_fix: false # it's needed for checking on multisong dataset if other is actually instrumental
  use_amp: true # enable or disable usage of mixed precision (float16) - usually it must be true

augmentations:
  enable: true # enable or disable all augmentations (to fast disable if needed)

  all:
    channel_shuffle: 0.5 # Set 0 or lower to disable
    random_inverse: 0.1 # inverse track (better lower probability)
    random_polarity: 0.5 # polarity change (multiply waveform to -1)


inference:
  extension: flac
  batch_size: 1
  dim_t: 256
  num_overlap: 8
```
