### ISSUE TITLE
Invalid shape for monophonic audio (augmentation) + Dataset 4 question

### ISSUE THREAD

**Issue by KatieBelli** [ZFTurbo/Music-Source-Separation-Training#135]
When I want to use augmentation this error appears (choosing only the channel_shuffle works fine though):

![Image](https://github.com/user-attachments/assets/6359bf99-c31f-42a6-9f09-d4fa727fd1ef)

I have mono files in my training dataset which were converted into stereo files before training (left and right channel containing the same audio).

What do I need to do to get rid of those 2 errors?

I use Prodigy as optimizer.

Here are the augmentations I intend to use (might want to use the other augmentations for other trainings):

```
augmentations:
  enable: true # enable or disable all augmentations (to fast disable if needed)
  loudness: true # randomly change loudness of each stem on the range (loudness_min; loudness_max)
  loudness_min: 0.5
  loudness_max: 1.5
  
  all:
    channel_shuffle: 0.5 # Set 0 or lower to disable

    # pedalboard pitch shift block
    pedalboard_pitch_shift: 0.01
    pedalboard_pitch_shift_semitones_min: -8
    pedalboard_pitch_shift_semitones_max: 5

    # pedalboard resample block
    pedalboard_resample: 0.01
    pedalboard_resample_target_sample_rate_min: 4000
    pedalboard_resample_target_sample_rate_max: 44100

  Target:
    pitch_shift: 0.1
    pitch_shift_min_semitones: -8
    pitch_shift_max_semitones: 5
    seven_band_parametric_eq: 0.25
    seven_band_parametric_eq_min_gain_db: -9
    seven_band_parametric_eq_max_gain_db: 9
    tanh_distortion: 0.1
    tanh_distortion_min: 0.1
    tanh_distortion_max: 0.7
  Other:
    pitch_shift: 0.1
    pitch_shift_min_semitones: -8
    pitch_shift_max_semitones: 5
    seven_band_parametric_eq: 0.25
    seven_band_parametric_eq_min_gain_db: -9
    seven_band_parametric_eq_max_gain_db: 9
    tanh_distortion: 0.1
    tanh_distortion_min: 0.1
    tanh_distortion_max: 0.7
```

**Other question:** Does this cause issues with the sync of Dataset 4? 

`min_mean_abs: 0.000`

My audio files are synced and them staying synced while training is crucial.
(The target stem and the other stem sometimes have silence but it's not many seconds. I had to change it to 0.000 or else it always shows an error during training.)
